"""raw message channel meta

Revision ID: 5747c1490cb6
Revises: 6f841cd15f16
Create Date: 2026-09-04 20:24:49.780646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5747c1490cb6"
down_revision: str | Sequence[str] | None = "6f841cd15f16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_channel_id", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("channel_meta", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_messages", schema=None) as batch_op:
        batch_op.drop_column("channel_meta")
        batch_op.drop_column("user_channel_id")

    # ### end Alembic commands ###
