"""sessions table

Revision ID: 6f841cd15f16
Revises: f8a74454e358
Create Date: 2026-08-26 21:07:39.696501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pocket.data.db

# revision identifiers, used by Alembic.
revision: str = "6f841cd15f16"
down_revision: str | Sequence[str] | None = "f8a74454e358"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("expires_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
