"""savings goals

Revision ID: 5c8e9d661db7
Revises: c26b92c29e19
Create Date: 2026-09-27 11:35:11.780791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pocket.data.db

# revision identifiers, used by Alembic.
revision: str = "5c8e9d661db7"
down_revision: str | Sequence[str] | None = "c26b92c29e19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("target_minor", sa.Integer(), nullable=False),
        sa.Column("due", pocket.data.db.UTCDateTime(), nullable=True),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("done_at", pocket.data.db.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goals")
    # ### end Alembic commands ###
