"""initial schema

Revision ID: f8a74454e358
Revises:
Create Date: 2026-08-16 11:41:06.544814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pocket.data.db

# revision identifiers, used by Alembic.
revision: str = "f8a74454e358"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("primary_channel", sa.String(length=16), nullable=True),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("archived_at", pocket.data.db.UTCDateTime(), nullable=True),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    op.create_table(
        "pending_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("expires_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "raw_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("channel_msg_id", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("media_json", sa.JSON(), nullable=True),
        sa.Column("received_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("processed_at", pocket.data.db.UTCDateTime(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "channel_msg_id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("channel_user_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "channel_user_id"),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=True),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("request_json", sa.JSON(), nullable=True),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index("ix_llm_calls_created", ["created_at"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_base_minor", sa.Integer(), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("merchant", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("occurred_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=True),
        sa.Column("llm_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("deleted_at", pocket.data.db.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_user_cat_occurred",
            ["user_id", "category_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_transactions_user_occurred", ["user_id", "occurred_at"], unique=False
        )

    op.create_table(
        "transaction_tags",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id"),
    )
    with op.batch_alter_table("transaction_tags", schema=None) as batch_op:
        batch_op.create_index("ix_transaction_tags_tag_id", ["tag_id"], unique=False)

    op.create_table(
        "transaction_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("changed_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("changed_by", sa.String(length=10), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transaction_versions_transaction_id"), ["transaction_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_versions_transaction_id"))

    op.drop_table("transaction_versions")
    with op.batch_alter_table("transaction_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_transaction_tags_tag_id")

    op.drop_table("transaction_tags")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_user_occurred")
        batch_op.drop_index("ix_transactions_user_cat_occurred")

    op.drop_table("transactions")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_calls_created")

    op.drop_table("llm_calls")
    op.drop_table("user_identities")
    op.drop_table("tags")
    op.drop_table("raw_messages")
    op.drop_table("pending_actions")
    op.drop_table("categories")
    op.drop_table("users")
    # ### end Alembic commands ###
