"""document imports

Revision ID: d8dbf6c53839
Revises: fbf0bfbdd63d
Create Date: 2026-10-07 22:24:43.342820

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pocket.data.db

# revision identifiers, used by Alembic.
revision: str = "d8dbf6c53839"
down_revision: str | Sequence[str] | None = "fbf0bfbdd63d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("mime", sa.String(length=80), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.Column("institution", sa.String(length=80), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("committed_at", pocket.data.db.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_imports_user_id"), ["user_id"], unique=False)

    op.create_table(
        "import_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("occurred_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("has_time", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_base_minor", sa.Integer(), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("merchant", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("category_hint", sa.String(length=80), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("duplicate_of", sa.Integer(), nullable=True),
        sa.Column("include", sa.Boolean(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_rows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_rows_import_id"), ["import_id"], unique=False)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("import_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_transactions_import_id"), ["import_id"], unique=False)
        batch_op.create_foreign_key("fk_transactions_import_id", "imports", ["import_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_transactions_import_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transactions_import_id"))
        batch_op.drop_column("import_id")

    with op.batch_alter_table("import_rows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_rows_import_id"))

    op.drop_table("import_rows")
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_imports_user_id"))

    op.drop_table("imports")
    # ### end Alembic commands ###
