"""budgets and recurring rules

Revision ID: c26b92c29e19
Revises: 5747c1490cb6
Create Date: 2026-09-05 16:07:17.771043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import pocket.data.db

# revision identifiers, used by Alembic.
revision: str = "c26b92c29e19"
down_revision: str | Sequence[str] | None = "5747c1490cb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=8), nullable=False),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category_id", "period"),
    )
    op.create_table(
        "recurring_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("merchant", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("cadence", sa.String(length=8), nullable=False),
        sa.Column("anchor", sa.Integer(), nullable=True),
        sa.Column("next_run", pocket.data.db.UTCDateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_posted_at", pocket.data.db.UTCDateTime(), nullable=True),
        sa.Column("created_at", pocket.data.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recurring_rules", schema=None) as batch_op:
        batch_op.create_index("ix_recurring_next", ["active", "next_run"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recurring_rules", schema=None) as batch_op:
        batch_op.drop_index("ix_recurring_next")

    op.drop_table("recurring_rules")
    op.drop_table("budgets")
    # ### end Alembic commands ###
